name: polaris-iam apply

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".gitignore"

jobs:
  github:
    concurrency: github
    uses: CloudCitizen/github-reusable-workflows/.github/workflows/terraform-apply.yaml@testworkflows
    with:
      file_path: "live/github"
    secrets:
      AWS_REGION:          ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID:      ${{ secrets.AWS_ACCOUNT_ID }}
