name: polaris-iam PR

on:
  pull_request:
    branches:
      - main

jobs:
  pre_commit:
    uses: CloudCitizen/github-reusable-workflows/.github/workflows/pre-commit.yaml@testworkflows

  tfsec:
    uses: CloudCitizen/github-reusable-workflows/.github/workflows/tfsec.yaml@testworkflows

  github:
    concurrency: github
    uses: CloudCitizen/github-reusable-workflows/.github/workflows/terraform-plan.yaml@testworkflows
    with:
      file_path: "live/github"
    secrets:
      AWS_REGION:          ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID:      ${{ secrets.AWS_ACCOUNT_ID }}
